apiVersion: v1
kind: Service
metadata:
  name: go-http-app-service
  namespace: logging
spec:
  selector:
    app: go-http-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
